Update streamlit_app.py
EkaterinaVZ/fill-mask pull request #14
Opened 2022-06-06 17:56 UTC by EkaterinaVZ

Внесены исправления в части оформления кода (в учебных целях, для проведения код-ревью)

2022-06-06 18:36 UTC, BabiiIn commented on streamlit_app.py
> +import time, streamlit as st
В соответствии с РЕР 8 подключение библиотек (импорты) выполнить в отдельных строках и расположить их в начале файла

2022-06-06 18:41 UTC, BabiiIn commented on streamlit_app.py
> +a, b = st.columns([1, 1])
В соответствии с руководством по стилю кода предлагаю переменные a и b назвать col1 и col2

2022-06-06 18:43 UTC, BabiiIn requested changes
В соответствии с РЕР 8 в код нужно внести изменения. Предложение по изменению указаны в коде

2022-06-06 21:18 UTC, moriys commented on streamlit_app.py
> +import time, streamlit as st
Согласна с комментарием

2022-06-06 21:18 UTC, moriys commented on streamlit_app.py
> +a, b = st.columns([1, 1])
Поддерживаю!

2022-06-06 21:19 UTC, moriys requested changes
Необходимо отредактировать с учетом комментариев Инессы

2022-06-07 03:19 UTC, Alexey26101980 commented on streamlit_app.py
>  def load_model():
Ok

2022-06-07 03:19 UTC, Alexey26101980 commented on streamlit_app.py
> +import time, streamlit as st
Да, согласен, так правильнее будет. Сразу можно будет видеть с какими библиотеками работаем.

2022-06-07 03:19 UTC, Alexey26101980 commented on streamlit_app.py
> +a, b = st.columns([1, 1])
Ok

2022-06-07 03:27 UTC, Alexey26101980 commented
Вносим изменения.

2022-06-07 03:37 UTC, Alexey26101980 commented
предлагаю сделать это.

2022-06-18 13:14 UTC, Alexey26101980 requested changes

2022-06-18 13:14 UTC, Alexey26101980 commented on streamlit_app.py
>  def load_model():
Поддерживаю.

2022-06-18 13:14 UTC, Alexey26101980 commented on streamlit_app.py
> +import time, streamlit as st
Согласен.

2022-06-18 13:14 UTC, Alexey26101980 commented on streamlit_app.py
> +a, b = st.columns([1, 1])
Будет лучше.

2022-06-20 16:44 UTC, EkaterinaVZ commented on streamlit_app.py
> +import time, streamlit as st
Импорты вынесены в начало файла

2022-06-20 16:44 UTC, EkaterinaVZ commented on streamlit_app.py
> +a, b = st.columns([1, 1])
Изменены названия переменных

2022-06-20 16:47 UTC, Alexey26101980 commented
Все скорректировано.

2022-06-20 16:48 UTC, Alexey26101980 approved these changes

2022-06-20 16:53 UTC, BabiiIn commented
Теперь все правильно. Можно сливать

2022-06-20 16:54 UTC, BabiiIn approved these changes
Теперь все правильно, можно сливать

2022-06-20 16:55 UTC, moriys approved these changes
Исправления корректны, можно сливать.

2022-06-20 16:56 UTC, merged